version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123                  # Password untuk root (optional)
      MYSQL_DATABASE: db_lansia                    # DB awal (boleh diubah)
      MYSQL_USER: lansia
      MYSQL_PASSWORD: lansia321
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # API untuk Data Jatuh
  api-fall:
    build: ./api-fall
    container_name: api_fall
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./api-fall:/var/www/html
    depends_on:
      - mysql

  # API untuk Data Tracking GPS
  api-tracking:
    build: ./api-tracking
    container_name: api_tracking
    restart: always
    ports:
      - "8003:80"
    volumes:
      - ./api-tracking:/var/www/html
    depends_on:
      - mysql

  # API untuk Data Lansia
  api-lansia:
    build: ./api-lansia
    container_name: api_lansia
    restart: always
    ports:
      - "8004:80"
    volumes:
      - ./api-lansia:/var/www/html
    depends_on:
      - mysql

  # API untuk Riwayat Gabungan
  api-riwayat:
    build: ./api-riwayat
    container_name: api_riwayat
    restart: always
    ports:
      - "8005:80"
    volumes:
      - ./api-riwayat:/var/www/html
    depends_on:
      - mysql
      
  api-notification:
    build: ./api-notification
    container_name: api_notification
    restart: always
    ports:
      - "8006:80"
    volumes:
      - ./api-notification:/var/www/html

  # phpMyAdmin
  # Buat Username : root
  # dan Password : root123
  # agar memiliki aksess tambah database baru
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
      PMA_ARBITRARY: 1

volumes:
  mysql-data:
